storage:
  parts_directory:  /Users/irinatomic/Documents/RAF/5. semestar/paralelni/project_files/file_parts
  saved_directory: /Users/irinatomic/Documents/RAF/5. semestar/paralelni/project_files/saved_files
system:
  io_processes: 8
  part_size:  1048576          # 1 megabyte = 1024 * 1024 bytes
  ram: 5242880                # 5 megabytew = 5 * 1024 * 1024 bytes